os: linux
language: python
branches:
  only:
  - gh-pages
  - /.*/
script: 
  - echo "Rebuild binder image"
after_success:
  - bash binder/trigger_binder.sh https://gke.mybinder.org/build/gh/johntfoster/numerical_methods_book/"${TRAVIS_BRANCH}"
  - bash binder/trigger_binder.sh https://ovh.mybinder.org/build/gh/johntfoster/numerical_methods_book/"${TRAVIS_BRANCH}"
